import 'package:office_work/data/model/book_model.dart';

List<BooksModel> booksList = [
  BooksModel(
    icon: 'assets/images/green_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/blue_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/red_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/green_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/blue_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/red_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/green_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/blue_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/red_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/green_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/blue_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/red_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/green_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/blue_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
  BooksModel(
    icon: 'assets/images/red_polygon.svg',
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
  ),
];
