import 'package:flutter/material.dart';
import 'package:office_work/core/assets/svg_path.dart';
import 'package:office_work/data/model/book_model.dart';

List<BooksModel> booksList = [
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xff1AA483),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xffFF2459),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xff3857BC),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xffDCB518),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xffED794D),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xff592BBB),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xffED794D),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xffDCB518),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color.fromARGB(157, 122, 24, 220),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color(0xff15C69B),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color.fromARGB(143, 3, 152, 38),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color.fromARGB(255, 62, 194, 231),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color.fromARGB(255, 220, 24, 27),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color.fromARGB(255, 121, 101, 25),
  ),
  BooksModel(
    icon: SvgPath.icPolygon,
    bookName: 'Book Name',
    writerName: 'Writer Name',
    totalHadith: 5235,
    book: 'Hadith',
    iconColor: const Color.fromARGB(255, 87, 20, 111),
  ),
];
